pipelines:
  default:
    - step:
        name: Run Playwright Tests
        image: mcr.microsoft.com/playwright:focal
        caches:
          - node
        script:
          - apt-get update && apt-get install -y openjdk-11-jdk
          - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
          - export PATH=$JAVA_HOME/bin:$PATH
          - npm ci
          - npx playwright install
          - npx playwright test
          - npx allure generate allure-results --clean -o allure-report
        artifacts:
          - allure-report/**