pipelines:
  default:
    - step:
        name: Run Playwright Tests
        image: mcr.microsoft.com/playwright:focal
        caches:
          - node
        script:
          - apt-get update && apt-get install -y openjdk-11-jdk
          - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
          - export PATH=$JAVA_HOME/bin:$PATH
          - npm ci
          - npx playwright install
          - npx playwright test
          - npx allure generate allure-results --clean -o docs
          - git config --global user.email "ci@bitbucket.org"
          - git config --global user.name "Bitbucket CI"
          - git add docs
          - git commit -m "Update Allure report"
          - git push origin HEAD
        artifacts:
          - docs/**